In [19]:
import pandas as pd

table = pd.read_csv("01102599999.csv")
temp_column = table["HourlyDryBulbTemperature"]
max_temp = temp_column.max()
max_temp_rows = table[table["HourlyDryBulbTemperature"] == max_temp]
max_temp_rows

C:\Users\Admin\AppData\Local\Temp\ipykernel_14496\3218557368.py:3: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  table = pd.read_csv("01102599999.csv")

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,REPORT_TYPE,SOURCE,HourlyAltimeterSetting,HourlyDewPointTemperature,...,BackupDirection,BackupDistance,BackupDistanceUnit,BackupElements,BackupElevation,BackupEquipment,BackupLatitude,BackupLongitude,BackupName,WindEquipmentChangeDate
9516,1102599999,2021-07-27T15:20:00,65.333333,7.316667,80.0,"HEIDRUN, NO",FM-15,4,29.83,57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9525,1102599999,2021-07-27T19:50:00,65.333333,7.316667,80.0,"HEIDRUN, NO",FM-15,4,29.83,55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN